# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SubWin_img_hist.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(946, 613)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.hist3 = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hist3.sizePolicy().hasHeightForWidth())
        self.hist3.setSizePolicy(sizePolicy)
        self.hist3.setMaximumSize(QtCore.QSize(448, 230))
        self.hist3.setObjectName("hist3")
        self.gridLayout.addWidget(self.hist3, 0, 1, 1, 1)
        self.Run = QtWidgets.QPushButton(self.centralwidget)
        self.Run.setMinimumSize(QtCore.QSize(460, 32))
        self.Run.setMaximumSize(QtCore.QSize(460, 32))
        self.Run.setObjectName("Run")
        self.gridLayout.addWidget(self.Run, 2, 1, 1, 1)
        self.origImage = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.origImage.sizePolicy().hasHeightForWidth())
        self.origImage.setSizePolicy(sizePolicy)
        self.origImage.setMinimumSize(QtCore.QSize(460, 32))
        self.origImage.setMaximumSize(QtCore.QSize(460, 32))
        self.origImage.setObjectName("origImage")
        self.gridLayout.addWidget(self.origImage, 2, 0, 1, 1)
        self.destination = QtWidgets.QPushButton(self.centralwidget)
        self.destination.setObjectName("destination")
        self.gridLayout.addWidget(self.destination, 3, 0, 1, 1)
        self.hist2 = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hist2.sizePolicy().hasHeightForWidth())
        self.hist2.setSizePolicy(sizePolicy)
        self.hist2.setMaximumSize(QtCore.QSize(448, 229))
        self.hist2.setObjectName("hist2")
        self.gridLayout.addWidget(self.hist2, 1, 1, 1, 1)
        self.hist1 = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hist1.sizePolicy().hasHeightForWidth())
        self.hist1.setSizePolicy(sizePolicy)
        self.hist1.setMaximumSize(QtCore.QSize(448, 230))
        self.hist1.setObjectName("hist1")
        self.gridLayout.addWidget(self.hist1, 1, 0, 1, 1)
        self.Save = QtWidgets.QPushButton(self.centralwidget)
        self.Save.setObjectName("Save")
        self.gridLayout.addWidget(self.Save, 3, 1, 1, 1)
        self.OriginalImage = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OriginalImage.sizePolicy().hasHeightForWidth())
        self.OriginalImage.setSizePolicy(sizePolicy)
        self.OriginalImage.setMinimumSize(QtCore.QSize(230, 213))
        self.OriginalImage.setMaximumSize(QtCore.QSize(230, 213))
        self.OriginalImage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OriginalImage.setScaledContents(True)
        self.OriginalImage.setAlignment(QtCore.Qt.AlignCenter)
        self.OriginalImage.setObjectName("OriginalImage")
        self.gridLayout.addWidget(self.OriginalImage, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 946, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Run.setText(_translate("MainWindow", "Run"))
        self.origImage.setText(_translate("MainWindow", "Select Image"))
        self.destination.setText(_translate("MainWindow", "Select Directory to Save Transformed Image"))
        self.Save.setText(_translate("MainWindow", "Save"))
        self.OriginalImage.setText(_translate("MainWindow", "Original Image"))

